# DATASOURCE & JPA
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/PARKING_CONTROL"
    username: "postgres"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: update

# ACTUATOR/HEALTHCHECK
management:
  health:
    probes:
      enabled: true
  endpoint:
    health:
      show-details: always